"""Удалить ненужные поля

Revision ID: 537736d7f9f1
Revises: ef26665ffc7d
Create Date: 2026-05-13 18:57:09.547969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537736d7f9f1'
down_revision: Union[str, Sequence[str], None] = 'ef26665ffc7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('device_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
