"""Добавить relationship для модели Usersession

Revision ID: ef26665ffc7d
Revises: 1fe0e89a52c1
Create Date: 2026-05-13 05:40:15.524002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef26665ffc7d'
down_revision: Union[str, Sequence[str], None] = '1fe0e89a52c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
